export {  default as  Hero } from './Hero/Hero';
export {  default as  Text } from './Text/Text';
export {  default as  Features } from './Features/Features';
export {  default as  ContactButton } from './ContactButton/ContactButton';
export {  default as  Footer } from './Footer/Footer';
export {  default as  FeaturePage1 } from './Pages/FeaturePage1/FeaturePage1';
export {  default as  FeaturePage2 } from './Pages/FeaturePage2/FeaturePage2';
export {  default as  FeaturePage3 } from './Pages/FeaturePage3/FeaturePage3';
export {  default as  SignUpForm } from './SignUpForm/SignUpForm';